/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCardResponseFromDiscriminatorValue, serializeCardCreateRequest, type CardCreateRequest, type CardResponse } from '../models/index.js';
// @ts-ignore
import { CardItemRequestBuilderRequestsMetadata, type CardItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /card
 */
export interface CardRequestBuilder extends BaseRequestBuilder<CardRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.card.item collection
     * @param id Unique identifier of the item
     * @returns {CardItemRequestBuilder}
     */
     byId(id: Guid) : CardItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CardResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<CardRequestBuilderGetQueryParameters> | undefined) : Promise<CardResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: CardCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CardRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CardCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface CardRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const CardRequestBuilderUriTemplate = "{+baseurl}/card{?id*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CardRequestBuilderNavigationMetadata: Record<Exclude<keyof CardRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CardItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CardRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CardRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createCardResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: CardRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCardCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
