/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type DateOnly, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdentityError}
 */
// @ts-ignore
export function createIdentityErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIdentityError;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponse}
 */
// @ts-ignore
export function createLoginResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MdFileResponse}
 */
// @ts-ignore
export function createMdFileResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMdFileResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MdFileUploadRequest}
 */
// @ts-ignore
export function createMdFileUploadRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMdFileUploadRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterRequest}
 */
// @ts-ignore
export function createRegisterRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserInfoResponse}
 */
// @ts-ignore
export function createUserInfoResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserInfoResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserInfoUpdateRequest}
 */
// @ts-ignore
export function createUserInfoUpdateRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserInfoUpdateRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WeatherForecast}
 */
// @ts-ignore
export function createWeatherForecastFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWeatherForecast;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIdentityError(identityError: Partial<IdentityError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { identityError.code = n.getStringValue(); },
        "description": n => { identityError.description = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
        "rememberMe": n => { loginRequest.rememberMe = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponse(loginResponse: Partial<LoginResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { loginResponse.message = n.getStringValue(); },
        "success": n => { loginResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMdFileResponse(mdFileResponse: Partial<MdFileResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "content": n => { mdFileResponse.content = n.getStringValue(); },
        "fileName": n => { mdFileResponse.fileName = n.getStringValue(); },
        "id": n => { mdFileResponse.id = n.getGuidValue(); },
        "uploadedAt": n => { mdFileResponse.uploadedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMdFileUploadRequest(mdFileUploadRequest: Partial<MdFileUploadRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "content": n => { mdFileUploadRequest.content = n.getStringValue(); },
        "name": n => { mdFileUploadRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { problemDetails.errorEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterRequest(registerRequest: Partial<RegisterRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerRequest.email = n.getStringValue(); },
        "password": n => { registerRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserInfoResponse(userInfoResponse: Partial<UserInfoResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { userInfoResponse.email = n.getStringValue(); },
        "isEmailConfirmed": n => { userInfoResponse.isEmailConfirmed = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserInfoUpdateRequest(userInfoUpdateRequest: Partial<UserInfoUpdateRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "newEmail": n => { userInfoUpdateRequest.newEmail = n.getStringValue(); },
        "newPassword": n => { userInfoUpdateRequest.newPassword = n.getStringValue(); },
        "oldPassword": n => { userInfoUpdateRequest.oldPassword = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWeatherForecast(weatherForecast: Partial<WeatherForecast> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "date": n => { weatherForecast.date = n.getDateOnlyValue(); },
        "summary": n => { weatherForecast.summary = n.getStringValue(); },
        "temperatureC": n => { weatherForecast.temperatureC = n.getNumberValue(); },
        "temperatureF": n => { weatherForecast.temperatureF = n.getNumberValue(); },
    }
}
export interface IdentityError extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The description property
     */
    description?: string | null;
}
export interface LoginRequest extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The rememberMe property
     */
    rememberMe?: boolean | null;
}
export interface LoginResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface MdFileResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The content property
     */
    content?: string | null;
    /**
     * The fileName property
     */
    fileName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The uploadedAt property
     */
    uploadedAt?: Date | null;
}
export interface MdFileUploadRequest extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The content property
     */
    content?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The error property
     */
    errorEscaped?: string | null;
}
export interface RegisterRequest extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIdentityError(writer: SerializationWriter, identityError: Partial<IdentityError> | undefined | null = {}) : void {
    if (identityError) {
        writer.writeStringValue("code", identityError.code);
        writer.writeStringValue("description", identityError.description);
        writer.writeAdditionalData(identityError.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}) : void {
    if (loginRequest) {
        writer.writeStringValue("email", loginRequest.email);
        writer.writeStringValue("password", loginRequest.password);
        writer.writeBooleanValue("rememberMe", loginRequest.rememberMe);
        writer.writeAdditionalData(loginRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponse(writer: SerializationWriter, loginResponse: Partial<LoginResponse> | undefined | null = {}) : void {
    if (loginResponse) {
        writer.writeStringValue("message", loginResponse.message);
        writer.writeBooleanValue("success", loginResponse.success);
        writer.writeAdditionalData(loginResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMdFileResponse(writer: SerializationWriter, mdFileResponse: Partial<MdFileResponse> | undefined | null = {}) : void {
    if (mdFileResponse) {
        writer.writeStringValue("content", mdFileResponse.content);
        writer.writeStringValue("fileName", mdFileResponse.fileName);
        writer.writeGuidValue("id", mdFileResponse.id);
        writer.writeDateValue("uploadedAt", mdFileResponse.uploadedAt);
        writer.writeAdditionalData(mdFileResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMdFileUploadRequest(writer: SerializationWriter, mdFileUploadRequest: Partial<MdFileUploadRequest> | undefined | null = {}) : void {
    if (mdFileUploadRequest) {
        writer.writeStringValue("content", mdFileUploadRequest.content);
        writer.writeStringValue("name", mdFileUploadRequest.name);
        writer.writeAdditionalData(mdFileUploadRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}) : void {
    if (problemDetails) {
        writer.writeStringValue("error", problemDetails.errorEscaped);
        writer.writeAdditionalData(problemDetails.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterRequest(writer: SerializationWriter, registerRequest: Partial<RegisterRequest> | undefined | null = {}) : void {
    if (registerRequest) {
        writer.writeStringValue("email", registerRequest.email);
        writer.writeStringValue("password", registerRequest.password);
        writer.writeAdditionalData(registerRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserInfoResponse(writer: SerializationWriter, userInfoResponse: Partial<UserInfoResponse> | undefined | null = {}) : void {
    if (userInfoResponse) {
        writer.writeStringValue("email", userInfoResponse.email);
        writer.writeBooleanValue("isEmailConfirmed", userInfoResponse.isEmailConfirmed);
        writer.writeAdditionalData(userInfoResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserInfoUpdateRequest(writer: SerializationWriter, userInfoUpdateRequest: Partial<UserInfoUpdateRequest> | undefined | null = {}) : void {
    if (userInfoUpdateRequest) {
        writer.writeStringValue("newEmail", userInfoUpdateRequest.newEmail);
        writer.writeStringValue("newPassword", userInfoUpdateRequest.newPassword);
        writer.writeStringValue("oldPassword", userInfoUpdateRequest.oldPassword);
        writer.writeAdditionalData(userInfoUpdateRequest.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWeatherForecast(writer: SerializationWriter, weatherForecast: Partial<WeatherForecast> | undefined | null = {}) : void {
    if (weatherForecast) {
        writer.writeDateOnlyValue("date", weatherForecast.date);
        writer.writeStringValue("summary", weatherForecast.summary);
        writer.writeNumberValue("temperatureC", weatherForecast.temperatureC);
        writer.writeNumberValue("temperatureF", weatherForecast.temperatureF);
        writer.writeAdditionalData(weatherForecast.additionalData);
    }
}
export interface UserInfoResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The isEmailConfirmed property
     */
    isEmailConfirmed?: boolean | null;
}
export interface UserInfoUpdateRequest extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The newEmail property
     */
    newEmail?: string | null;
    /**
     * The newPassword property
     */
    newPassword?: string | null;
    /**
     * The oldPassword property
     */
    oldPassword?: string | null;
}
export interface WeatherForecast extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The date property
     */
    date?: DateOnly | null;
    /**
     * The summary property
     */
    summary?: string | null;
    /**
     * The temperatureC property
     */
    temperatureC?: number | null;
    /**
     * The temperatureF property
     */
    temperatureF?: number | null;
}
/* tslint:enable */
/* eslint-enable */
