/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMdFileResponseFromDiscriminatorValue, serializeMdFileUploadRequest, type MdFileResponse, type MdFileUploadRequest } from '../models/index.js';
// @ts-ignore
import { MdfilesItemRequestBuilderRequestsMetadata, type MdfilesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /mdfiles
 */
export interface MdfilesRequestBuilder extends BaseRequestBuilder<MdfilesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.mdfiles.item collection
     * @param id Unique identifier of the item
     * @returns {MdfilesItemRequestBuilder}
     */
     byId(id: Guid) : MdfilesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MdFileResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<MdfilesRequestBuilderGetQueryParameters> | undefined) : Promise<MdFileResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     put(body: MdFileUploadRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MdfilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MdFileUploadRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface MdfilesRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const MdfilesRequestBuilderUriTemplate = "{+baseurl}/mdfiles{?id*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MdfilesRequestBuilderNavigationMetadata: Record<Exclude<keyof MdfilesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: MdfilesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MdfilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MdfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMdFileResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: MdfilesRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMdFileUploadRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
