/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithHeadingItemRequestBuilder, WithHeadingItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /mdfile/{id}/section
 */
export interface SectionRequestBuilder extends BaseRequestBuilder<SectionRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.mdfile.item.section.item collection
     * @param heading Unique identifier of the item
     * @returns {WithHeadingItemRequestBuilder}
     */
     byHeading(heading: string) : WithHeadingItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SectionRequestBuilderUriTemplate = "{+baseurl}/mdfile/{id}/section";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byHeading: {
        requestsMetadata: WithHeadingItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["heading"],
    },
};
/* tslint:enable */
/* eslint-enable */
