/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMdFileResponseFromDiscriminatorValue, type MdFileResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /mdfile/{id}
 */
export interface MdfileItemRequestBuilder extends BaseRequestBuilder<MdfileItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MdFileResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MdFileResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MdfileItemRequestBuilderUriTemplate = "{+baseurl}/mdfile/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MdfileItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MdfileItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createMdFileResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
