/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCardResponseFromDiscriminatorValue, type CardResponse } from '../models/index.js';
// @ts-ignore
import { CardsItemRequestBuilderRequestsMetadata, type CardsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /cards
 */
export interface CardsRequestBuilder extends BaseRequestBuilder<CardsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.cards.item collection
     * @param id Unique identifier of the item
     * @returns {CardsItemRequestBuilder}
     */
     byId(id: Guid) : CardsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CardResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<CardsRequestBuilderGetQueryParameters> | undefined) : Promise<CardResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CardsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface CardsRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const CardsRequestBuilderUriTemplate = "{+baseurl}/cards{?id*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CardsRequestBuilderNavigationMetadata: Record<Exclude<keyof CardsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CardsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CardsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CardsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createCardResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
